from fpdf import FPDF
import tempfile
import os
import matplotlib.pyplot as plt
import seaborn as sns
import io

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        # Add Logo if available (placeholder logic)
        # self.image('logo.png', 10, 8, 33)
        self.cell(0, 10, 'UIDAI Satark - District Strategy Report', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by Aadhaar Satark System - Confidential Government Document', 0, 0, 'C')
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'R')

def generate_chart(district_name, expected, actual):
    """Generates a comparison chart and returns the temp file path."""
    plt.figure(figsize=(6, 4))
    sns.set_theme(style="whitegrid")
    
    data = {'Metric': ['Expected (Tm)', 'Actual (Am)'], 'Count': [expected, actual]}
    colors = ['#3B82F6', '#10B981'] # Blue, Emerald
    
    ax = sns.barplot(x='Metric', y='Count', data=data, palette=colors)
    ax.set_title(f'Biometric Update Status: {district_name}', fontsize=12, pad=10)
    ax.set_ylabel("Records")
    
    # Add values on top of bars
    for i, v in enumerate([expected, actual]):
        ax.text(i, v + (expected * 0.02), f"{v:,}", ha='center', fontsize=10, fontweight='bold')

    plt.tight_layout()
    
    fd, path = tempfile.mkstemp(suffix=".png")
    plt.savefig(path, dpi=100)
    plt.close()
    os.close(fd)
    return path

def generate_report(district_data: dict) -> bytes:
    pdf = PDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Data Extraction
    district = district_data.get('district', 'N/A')
    state = district_data.get('state', 'N/A')
    expected = district_data.get('expected_updates', 0)
    actual = district_data.get('actual_updates', 0)
    pending = district_data.get('pending_updates', 0)
    gap = district_data.get('gap_percentage', 0)
    status = district_data.get('status', 'SAFE')
    efficiency = district_data.get('efficiency_index', 0.0)
    
    # 1. Title Section
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, txt=f"Strategy Report: {district.upper()}", ln=1)
    
    pdf.set_font("Arial", size=11)
    pdf.cell(0, 8, txt=f"Jurisdiction: {state} | Report Date: 2026-01-17", ln=1)
    pdf.ln(2)
    
    # 2. Logic for Narrative & Actions
    if status == "CRITICAL":
        summary = f"CRITICAL INTERVENTION REQUIRED. District {district} has flagged a {gap}% deficit in mandatory biometric updates. This is a severe backlog affecting service delivery for the 5-17 age group. Immediate mobilization of resources is required to prevent denial of service."
        action_plan = [
            "1. Deployment: Dispatch 5 Mobile Enrolment Units immediately to high-density school zones.",
            "2. Camp Mode: Initiate 'Mission Mode' camps on weekends for next 4 weeks.",
            "3. Notification: Bulk SMS broadcast to parents of pending applicants."
        ]
        color = (220, 38, 38) # Red
    elif status == "MODERATE":
        summary = f"WARNING ISSUED. District {district} is showing signs of update lag ({gap}%). While not yet critical, the trend indicates a potential bottleneck in 3 months. Pre-emptive measures are advised."
        action_plan = [
            "1. Capacity Boost: Extend operating hours of existing centers by 2 hours.",
            "2. School Liaison: Coordinate with local Education Officers for data matching.",
            "3. Monitoring: Weekly review of application rejection rates."
        ]
        color = (249, 115, 22) # Orange
    else:
        summary = f"OPERATIONAL NORMALCY. District {district} is performing within expected parameters ({gap}% variance). Maintain current operational tempo and focus on quality assurance."
        action_plan = [
            "1. Sustainment: Continue periodic monitoring.",
            "2. Optimization: Focus on reducing rejection rates.",
            "3. Excellence: Document best practices for state-level sharing."
        ]
        color = (22, 163, 74) # Green

    # 3. Status Banner
    pdf.set_fill_color(*color)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, txt=f"  ASSESSMENT LEVEL: {status}", ln=1, fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # 4. Executive Summary
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 8, txt="Executive Summary", ln=1)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 6, txt=summary)
    pdf.ln(5)

    # 5. Visual Analysis (Chart)
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 8, txt="Visual Variance Analysis", ln=1)
    # Generate and embed chart
    chart_path = generate_chart(district, expected, actual)
    pdf.image(chart_path, x=10, y=pdf.get_y(), w=100)
    pdf.ln(75) # Move cursor down past image
    os.remove(chart_path) # Cleanup

    # 6. Detailed Metrics Table
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 8, txt="Operational Metrics", ln=1)
    
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(70, 8, "Metric", 1, 0, 'L', True)
    pdf.cell(50, 8, "Value", 1, 1, 'L', True)
    
    pdf.set_font("Arial", size=10)
    data_rows = [
        ("Target Population (Expected)", f"{expected:,}"),
        ("Biometrics Completed (Actual)", f"{actual:,}"),
        ("Pending Backlog", f"{pending:,}"),
        ("Current Deficit", f"{gap}%"),
        ("Efficiency Index", f"{efficiency:.2f} (Norm: 1.0)"),
    ]
    
    for metric, value in data_rows:
        pdf.cell(70, 8, metric, 1)
        pdf.cell(50, 8, value, 1, 1)
    
    pdf.ln(5)

    # 7. Resource Planning (The "Value Add")
    # Assumption: 1 Operator can do 50 updates/day.
    # Goal: Clear backlog in 30 days.
    if pending > 0:
        updates_per_day_needed = pending / 30
        kits_needed = updates_per_day_needed / 50
        kits_needed = max(1, round(kits_needed)) # Minimum 1 kit
        
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(0, 8, txt="Resource Planning (30-Day Resolution Plan)", ln=1)
        pdf.set_font("Arial", 'I', 10)
        pdf.multi_cell(0, 6, txt=f"To clear the pending backlog of {pending:,} records within 30 days, assuming a standard throughput of 50 updates/kit/day:")
        pdf.ln(2)
        
        pdf.set_font("Arial", 'B', 10)
        pdf.cell(90, 8, "Required Daily Throughput:", 1)
        pdf.cell(40, 8, f"{int(updates_per_day_needed)} updates/day", 1, 1)
        pdf.cell(90, 8, "Additional Enrolment Kits Required:", 1)
        pdf.cell(40, 8, f"{kits_needed} Kits", 1, 1)
        pdf.ln(5)

    # 8. Strategic Action Plan
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 8, txt="Official Directives", ln=1)
    pdf.set_font("Arial", size=10)
    for action in action_plan:
        pdf.multi_cell(0, 6, txt=action)
        pdf.ln(2)
    
    pdf.ln(10)
    
    # 9. Sign-off Area
    y = pdf.get_y()
    pdf.line(10, y, 90, y)
    pdf.line(110, y, 190, y)
    pdf.ln(2)
    pdf.cell(80, 5, "District Nodal Officer", 0, 0, 'C')
    pdf.cell(20, 5, "", 0, 0)
    pdf.cell(80, 5, "UIDAI Regional Office", 0, 1, 'C')

    return pdf.output(dest='S').encode('latin-1')
